name: deploy

on:
  workflow_dispatch:

jobs:

  pypi:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Pin build backend
        run: |
          echo 'hatchling==1.14.0' > "${{ runner.temp }}/constraints.txt"
      - name: Package
        env:
          PIP_CONSTRAINT: ${{ runner.temp }}/constraints.txt
          PIP_INDEX_URL: 'https://:2023-04-16@time-machines-pypi.sealsecurity.io/'
        run: |
          pip install --upgrade build
          python -m build -s -w
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: pypi-distributions
          path: dist/*
          if-no-files-found: error
